version: '3.8'

services:
  backend:
    container_name: backend-container
    build:
      context: ../example-backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    container_name: frontend-container
    build:
      context: ../example-frontend
    ports:
      - "5007:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork: